# Generated by Django 4.2.7 on 2023-11-22 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employed', models.DateTimeField()),
                ('national_identity', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(choices=[('Administration', 'Adm'), ('Security', 'Sec'), ('Management', 'Mgt'), ('Field', 'Fld'), ('Office', 'Off'), ('Stores', 'Str'), ('Other', 'Other')], max_length=100)),
                ('position', models.CharField(choices=[('Guard', 'Grd'), ('Plucker', 'Plk'), ('Dairy', 'Dairy'), ('Kando', 'Kando'), ('Cook', 'Ck'), ('Office Messanger', 'Off Mgr'), ('Store', 'Str'), ('Director', 'Dir'), ('Estate Worker', 'Est Wkr'), ('Assistant Manager', 'Asst Mgr'), ('Accountant', 'Acct'), ('Supervisor', 'Sup'), ('Clerk', 'Clk')], max_length=100)),
                ('salary_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=20)),
                ('fertilizer_applied', models.DateTimeField()),
                ('fertilizer_amt', models.IntegerField()),
                ('fertilizer_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_labour', models.IntegerField()),
                ('fertilizer_labour_cost', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_price', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fertilizer_total_cost', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Green',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plucking_date', models.DateTimeField()),
                ('green_data', models.CharField(default=False, max_length=50)),
                ('green_today', models.IntegerField()),
                ('green_todate', models.IntegerField(blank=True, null=True)),
                ('plucker_numbers', models.IntegerField()),
                ('total_pluckers', models.IntegerField(blank=True, null=True)),
                ('plucking_average', models.IntegerField(blank=True, null=True)),
                ('total_green', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KandojobsPruning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruning_done', models.DateTimeField()),
                ('pruned_block_no', models.IntegerField()),
                ('pruned_bushes', models.IntegerField()),
                ('total_pruned_bushes', models.IntegerField(blank=True, null=True)),
                ('pruning_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('pruning_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='KandojobsWeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeding_done', models.DateTimeField(default=None)),
                ('chemical_name', models.CharField(default=None, max_length=100)),
                ('block_no', models.IntegerField()),
                ('cost_per_lit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_chem_amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_chem_amt', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour_number', models.IntegerField(default=None)),
                ('total_weeding_labour_number', models.IntegerField(default=None)),
                ('weeding_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour', models.IntegerField()),
                ('weeding_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_done', models.DateTimeField()),
                ('milk_today', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_todate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cows_milked', models.IntegerField()),
                ('cow_numbers', models.IntegerField()),
                ('milking_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_milk', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Purple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plucking_date', models.DateTimeField()),
                ('purple_data', models.CharField(default=False, max_length=50)),
                ('purple_today', models.IntegerField()),
                ('purple_todate', models.IntegerField(blank=True, null=True)),
                ('plucker_numbers', models.IntegerField()),
                ('total_pluckers', models.IntegerField(blank=True, null=True)),
                ('plucking_average', models.IntegerField(blank=True, null=True)),
                ('total_purple', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_report', models.CharField(max_length=2000)),
                ('visitors_name', models.CharField(max_length=100)),
                ('visitor_comments', models.CharField(max_length=2000)),
                ('farm_report', models.CharField(max_length=2000)),
                ('farm_requirements', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='VetCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calf_down', models.DateTimeField(auto_now_add=True)),
                ('today', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 22, 17, 20, 10, 19232))),
                ('calf_age', models.IntegerField(default=None)),
                ('calf_numbers', models.IntegerField(blank=True)),
                ('vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('total_vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
    ]
