# Generated by Django 4.1.4 on 2023-04-21 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employed', models.DateTimeField()),
                ('national_identity', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(choices=[('Adm', 'Administration'), ('Sec', 'Security'), ('Mangt', 'Management'), ('Field', 'Field'), ('Off', 'Office'), ('Other', '')], max_length=100)),
                ('position', models.CharField(choices=[('Dir', 'Director'), ('Mng', 'Manager'), ('Acct', 'Accountant'), ('Sup', 'Supervisor'), ('Clk', 'Clerk'), ('plk', 'Plucker'), ('Dairy', 'DairyWorker'), ('Kando', 'Kando Worker'), ('Cook', 'Cook'), ('grd', 'Guard')], max_length=100)),
                ('salary', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=20)),
                ('fertilizer_applied', models.DateTimeField()),
                ('fertilizer_amt', models.IntegerField()),
                ('fertilizer_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_labour', models.IntegerField()),
                ('fertilizer_labour_cost', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_price', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fertilizer_total_cost', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Green',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plucking_date', models.DateTimeField()),
                ('green_data', models.CharField(default=False, max_length=50)),
                ('green_today', models.IntegerField()),
                ('green_todate', models.IntegerField(blank=True, null=True)),
                ('plucker_numbers', models.IntegerField()),
                ('total_pluckers', models.IntegerField(blank=True, null=True)),
                ('plucking_average', models.IntegerField(blank=True, null=True)),
                ('total_green', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kandojobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruning_done', models.DateTimeField()),
                ('pruned_block_No', models.IntegerField()),
                ('pruned_bushes', models.IntegerField()),
                ('total_pruned_bushes', models.IntegerField(default=None)),
                ('pruning_rate', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('pruning_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_done', models.DateTimeField(default=None)),
                ('chemical_name', models.CharField(default=None, max_length=100)),
                ('block_No', models.IntegerField(default=None)),
                ('cost_per_lit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_chem_amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_chem_amt', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour_number', models.IntegerField(default=None)),
                ('total_weeding_labour_number', models.IntegerField(default=None)),
                ('weeding_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour', models.IntegerField(default=None)),
                ('weeding_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_done', models.DateTimeField()),
                ('milk_today', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_todate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cows_milked', models.IntegerField()),
                ('cow_numbers', models.IntegerField()),
                ('milking_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_milk', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calf_down', models.DateTimeField(auto_now_add=True)),
                ('today', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 10, 13, 57, 991159))),
                ('calf_age', models.IntegerField(default=None)),
                ('calf_numbers', models.IntegerField(blank=True)),
                ('vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('Total_vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Purple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plucking_date', models.DateTimeField()),
                ('purple_data', models.CharField(default=False, max_length=50)),
                ('purple_today', models.IntegerField()),
                ('purple_todate', models.IntegerField(blank=True, null=True)),
                ('plucker_numbers', models.IntegerField()),
                ('total_pluckers', models.IntegerField(blank=True, null=True)),
                ('plucking_average', models.IntegerField(blank=True, null=True)),
                ('total_purple', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
