# Generated by Django 4.2.7 on 2023-11-22 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeding_done', models.DateTimeField(default=None)),
                ('chemical_name', models.CharField(default=None, max_length=100)),
                ('block_no', models.IntegerField()),
                ('cost_per_lit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_chem_amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_chem_amt', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour_number', models.IntegerField(default=None)),
                ('total_weeding_labour_number', models.IntegerField(default=None)),
                ('weeding_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour', models.IntegerField()),
                ('weeding_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='KandojobsPruning',
            new_name='Pruning',
        ),
        migrations.DeleteModel(
            name='KandojobsWeeding',
        ),
        migrations.AlterField(
            model_name='vetcosts',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 22, 21, 15, 35, 127969)),
        ),
    ]
