# Generated by Django 4.2.3 on 2023-11-14 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 14, 17, 48, 9, 435275)),
        ),
    ]
