# Generated by Django 4.1.4 on 2023-05-05 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_identity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 23, 35, 32, 526034)),
        ),
    ]
