# Generated by Django 4.1.4 on 2023-04-21 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandojobs',
            name='pruning_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 12, 5, 2, 384689)),
        ),
    ]
