# Generated by Django 4.2.3 on 2023-11-15 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0002_reports_image_alter_milk_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='image',
        ),
        migrations.AddField(
            model_name='reports',
            name='farm_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 15, 17, 50, 32, 811206)),
        ),
    ]
