# Generated by Django 4.0.4 on 2022-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0002_delete_cashbreakdown_crop_total_pluckers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandojobs',
            name='total_chem_amt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AddField(
            model_name='kandojobs',
            name='total_pruned_bushes',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='kandojobs',
            name='total_weeding_labour_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='milk',
            name='calf_age',
            field=models.IntegerField(default=None),
        ),
    ]
