# Generated by Django 4.1.4 on 2023-05-05 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0002_alter_employee_national_identity_alter_milk_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='No_Employees',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_avg',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_sum',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total',
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 23, 36, 41, 130760)),
        ),
    ]
