# Generated by Django 4.2.7 on 2023-11-22 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0002_weeding_rename_kandojobspruning_pruning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetcosts',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 22, 23, 22, 11, 333036)),
        ),
    ]
