# Generated by Django 4.0.4 on 2022-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0003_kandojobs_total_chem_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='calf_down',
            field=models.DateField(auto_now_add=True),
        ),
    ]
