# Generated by Django 4.1.4 on 2023-05-09 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0003_remove_employee_no_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_report', models.CharField(max_length=250)),
                ('visitors_name', models.CharField(max_length=100)),
                ('visitor_comments', models.CharField(max_length=100)),
                ('farm_report', models.CharField(max_length=100)),
                ('farm_requirements', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 9, 20, 58, 25, 691534)),
        ),
    ]
