# Generated by Django 4.2.7 on 2023-11-24 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0004_alter_vetcosts_today_alter_weeding_block_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetcosts',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 24, 21, 36, 3, 825835)),
        ),
    ]
