# Generated by Django 4.0.4 on 2022-11-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0004_alter_milk_calf_down'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops_P',
            new_name='CropP',
        ),
        migrations.RenameField(
            model_name='cropp',
            old_name='crops_todate',
            new_name='crop_todate',
        ),
        migrations.RenameField(
            model_name='cropp',
            old_name='crops_today',
            new_name='crop_today',
        ),
        migrations.RemoveField(
            model_name='cropp',
            name='crops_data',
        ),
        migrations.AddField(
            model_name='cropp',
            name='crop_data',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
