# Generated by Django 4.0.4 on 2022-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0005_rename_crops_p_cropp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='calf_down',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
