# Generated by Django 3.0.2 on 2023-11-17 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0005_auto_20231117_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 17, 20, 47, 55, 769975)),
        ),
    ]
