# Generated by Django 4.0.4 on 2022-11-27 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0006_alter_milk_calf_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 13, 0, 36, 237673)),
        ),
    ]
