# Generated by Django 4.2.7 on 2023-11-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0007_auto_20231117_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='green',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kandojobs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 19, 15, 32, 53, 716939)),
        ),
        migrations.AlterField(
            model_name='purple',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='daily_report',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='farm_report',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='farm_requirements',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reports',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='visitor_comments',
            field=models.CharField(max_length=2000),
        ),
    ]
