# Generated by Django 4.0.4 on 2022-11-27 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0007_milk_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 13, 4, 54, 57748)),
        ),
    ]
